/**
 * Builds the blur placeholder map consumed by lib/blur.js.
 *
 * next/image only derives a blurDataURL automatically for statically imported
 * images. Every image here is referenced by path (from lib/gallery.js,
 * lib/pricing.js, lib/site.js), so the placeholders have to be baked ahead of
 * time — otherwise the grid renders 24 empty boxes that snap to full colour
 * one by one.
 *
 * Each entry is a 12px-wide WebP, ~200-400 bytes, which next/image scales up
 * and blurs behind the real image.
 *
 *   node scripts/generate-blur.mjs
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const ROOT = path.join(process.cwd(), 'public')
const OUT = path.join(process.cwd(), 'lib', 'blurData.js')

/** Only the folders whose images are rendered through next/image. */
const INCLUDE = [/^gallery\//, /^backgrounds\//]

const walk = async (dir) => {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const files = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name)
      return entry.isDirectory() ? walk(full) : [full]
    }),
  )
  return files.flat()
}

const run = async () => {
  const files = (await walk(ROOT))
    .filter((f) => /\.(webp|jpe?g|png)$/i.test(f))
    .map((f) => path.relative(ROOT, f).split(path.sep).join('/'))
    .filter((rel) => INCLUDE.some((pattern) => pattern.test(rel)))
    .sort()

  const entries = []

  for (const rel of files) {
    const buffer = await sharp(path.join(ROOT, rel))
      .resize(12, null, { fit: 'inside' })
      .webp({ quality: 45 })
      .toBuffer()

    entries.push(
      `  "/${rel}": "data:image/webp;base64,${buffer.toString('base64')}",`,
    )
  }

  const file = `/**
 * Generated by scripts/generate-blur.mjs — do not edit by hand.
 * Re-run \`npm run images\` after adding or replacing an image.
 */
const blurData = {
${entries.join('\n')}
}

export default blurData
`

  await fs.writeFile(OUT, file)

  const bytes = Buffer.byteLength(file)
  console.log(
    `${entries.length} placeholder(s) -> lib/blurData.js (${(bytes / 1024).toFixed(1)}KB)`,
  )
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
